### PR TITLE
Add basic desktop file checks

### PR DESCRIPTION
**Pull request by bbhtt**
Fixes https://github.com/flathub-infra/flatpak-builder-lint/issues/244

~~WIP I need to check if it breaks anything and add a few more checks.~~

### CODE REVIEW

**Comment by bbhtt** [comment]
The following recipe will reproduce the brokenness in #244. 

flatpak-builder (at least the version used in org.flatpak.Builder) happily returns success on the build. The libappstream port made things better by returning a bunch of errors, although that doesn't protect against direct uploads being broken.

<details> 
<summary> manifest </summary>

```json
{
    "app-id":"org.flathub.test",
    "runtime":"org.freedesktop.Platform",
    "runtime-version":"23.08",
    "sdk":"org.freedesktop.Sdk",
    "command":"echo",
    "finish-args":[
        "--device=dri"
    ],
    "modules":[
        {
            "name":"desktop",
            "buildsystem": "simple",
            "sources":[
                {
                    "type":"file",
                    "path":"org.flathub.test.desktop"
                },
                {
                    "type":"file",
                    "path":"foo.png"
                }
            ],
            "build-commands": [
                "mkdir -p /app/share/icons/hicolor/128x128/apps",
                "mkdir -p /app/bin",
                "touch /app/bin/echo",
                "mv foo.png /app/share/icons/hicolor/128x128/apps/",
                "install -Dm644 $FLATPAK_ID.desktop /app/share/applications/$FLATPAK_ID.desktop"
            ]
        }
    ]
}
```

```sh
$ cat org.flathub.test.desktop 

[Desktop Entry]
////=Bar
Exec=
Icon=foo
***=true
Terminal=false
Type=Application
Categories=Network;News;
Version=1.1
MimeType=application/rss+xml;application/atom+xml;application/rdf+xml;x-scheme-handler/feed
```

</details>

- `foo.png` is an actual 128px png icon

<details>
<summary> flatpak-builder output </summary>

```sh
flatpak run org.flatpak.Builder build org.flathub.test.json --disable-download --force-clean --repo=repo
Emptying app dir 'build'
Starting build of org.flathub.test
Cache miss, checking out last cache hit
========================================================================
Building module desktop in /home/bbhtt/Downloads/tests/org.flathub.test/.flatpak-builder/build/desktop-7
========================================================================
Running: mkdir -p /app/share/icons/hicolor/128x128/apps
Running: mkdir -p /app/bin
Running: touch /app/bin/echo
Running: mv foo.png /app/share/icons/hicolor/128x128/apps/
Running: install -Dm644 $FLATPAK_ID.desktop /app/share/applications/$FLATPAK_ID.desktop
Committing stage build-desktop to cache
Cleaning up
Committing stage cleanup to cache
Finishing app
Exporting share/applications/org.flathub.test.desktop
Not exporting share/icons/hicolor/128x128/apps/foo.png, non-allowed export filename
Please review the exported files and the metadata
Committing stage finish to cache
Exporting org.flathub.test to repo
WARNING: Failed to validate desktop file /home/bbhtt/Downloads/tests/org.flathub.test/build/export/share/applications/org.flathub.test.desktop: /home/bbhtt/Downloads/tests/org.flathub.test/build/export/share/applications/org.flathub.test.desktop: error: file contains key "////" in group "Desktop Entry", but key names must contain only the characters A-Za-z0-9- (they may have a "[LOCALE]" postfix)
/home/bbhtt/Downloads/tests/org.flathub.test/build/export/share/applications/org.flathub.test.desktop: error: file contains key "***" in group "Desktop Entry", but key names must contain only the characters A-Za-z0-9- (they may have a "[LOCALE]" postfix)
/home/bbhtt/Downloads/tests/org.flathub.test/build/export/share/applications/org.flathub.test.desktop: error: required key "Name" in group "Desktop Entry" is not present

WARNING: Icon not matching app id in /home/bbhtt/Downloads/tests/org.flathub.test/build/export/share/applications/org.flathub.test.desktop: foo
WARNING: Icon referenced in desktop file but not exported: foo
Commit: 46af1abfa65d6e5b9c6b075963e0d94fa0531f802cc94bfda7acec1540d5ddda
Metadata Total: 25
Metadata Written: 10
Content Total: 6
Content Written: 3
Content Bytes Written: 1224 (1.2 kB)
Pruning cache
```

<details>
<summary> linter output </summary>

```sh
→ flatpak-builder-lint builddir build                                                                            
{
    "errors": [
        "desktop-file-failed-validation",
        "appstream-metainfo-missing",
        "appstream-missing-appinfo-file",
        "desktop-file-empty-exec-key",
        "desktop-file-wrong-icon-name",
        "appstream-missing-icon-file"
    ],
    "desktopfile": [
        "error: required key \"Name\" in group \"Desktop Entry\" is not present",
        "error: file contains key \"////\" in group \"Desktop Entry\", but key names must contain only the characters A-Za-z0-9- (they may have a \"[LOCALE]\" postfix)",
        "error: file contains key \"***\" in group \"Desktop Entry\", but key names must contain only the characters A-Za-z0-9- (they may have a \"[LOCALE]\" postfix)"
    ]
}
x flatpak-builder-lint repo repo                                                                                 
{
    "errors": [
        "desktop-file-empty-exec-key",
        "desktop-file-failed-validation",
        "appstream-screenshots-not-mirrored-in-ostree",
        "desktop-file-wrong-icon-name"
    ],
    "desktopfile": [
        "error: file contains key \"////\" in group \"Desktop Entry\", but key names must contain only the characters A-Za-z0-9- (they may have a \"[LOCALE]\" postfix)",
        "error: file contains key \"***\" in group \"Desktop Entry\", but key names must contain only the characters A-Za-z0-9- (they may have a \"[LOCALE]\" postfix)",
        "error: required key \"Name\" in group \"Desktop Entry\" is not present"
    ]
```
</details>

All checks are skipped if for console applications, baseapps and extensions.

**Comment by hadess** [comment]
Looks good, thanks for working on this.

**Comment by bbhtt** [comment]
Some applications using extra-data write their desktop files directly to `export/share/applications` in manifest or through apply_extra https://github.com/search?q=org%3Aflathub+%22export%2Fshare%2Fapplications%2F%22&type=code

These will now get caught as `desktop-file-not-installed`. I think that location is meant to be used by flatpak/flatpak-builder only and not for manually placing desktop-files. Right now `org.flatpak.Builder` supports this case without any error, but with the libappstream port they fail:

```
Run failed, some data was ignored.
Errors were raised during this compose run:
general
  E: filters-but-no-output

com.viber.Viber.desktop
  E: no-stock-icon
```

I can add that location too if needed, but I think this usage should be caught.

**Comment by barthalion** [comment]
I think it's fair – just 10 apps (one is EOL), and not shipping desktop and icon files as part of the app has been historically causing issues here and there.

**Pull request merged**
