### PR TITLE
flathub_json: Disallow automerge unless extra-data

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by hfiguiere** [comment]
there are things like rust sdk that have automerge enabled. Given that they pull the official builds.

**Comment by bbhtt** [comment]
Yea I will add everything existing to exceptions.

**Comment by bbhtt** [comment]
List. Let me know if I'm missing any.

<details>

```
app.resp.RESP
app.xemu.xemu
ch.tlaun.TL
com.adilhanney.ricochlime
com.adilhanney.saber
com.amazon.Workspaces
com.atlauncher.ATLauncher
com.bitwarden.desktop
com.brave.Browser
com.budgetwithbuckets.Buckets
com.calibre_ebook.calibre
com.cassidyjames.butler
com.cassidyjames.plausible
com.chez.GrafX2
com.discordapp.Discord
com.discordapp.DiscordCanary
com.eduke32.EDuke32
com.emqx.MQTTX
com.fightcade.Fightcade
com.flashforge.FlashPrint
com.getpostman.Postman
com.gitbutler.gitbutler
com.github.Anuken.Mindustry
com.github.cassidyjames.clairvoyant
com.github.cfcurtis.pdfstitcher
com.github.libresprite.LibreSprite
com.github.LongSoft.UEFITool
com.github.marhkb.Pods
com.github.nihui.waifu2x-ncnn-vulkan
com.github.phase1geo.minder
com.github.reds.LogisimEvolution
com.github.skullernet.q2pro
com.gitlab.j0chn.nextcloud_password_client
com.google.ChromeDev
com.icons8.Lunacy
com.inochi2d.inochi-creator
com.jagex.RuneScape
com.lunarclient.LunarClient
com.microsoft.Edge
com.microsoft.EdgeDev
com.nextcloud.desktopclient.nextcloud
com.obsproject.Studio
com.obsproject.Studio.Plugin.Gstreamer
com.obsproject.Studio.Plugin.MoveTransition
com.obsproject.Studio.Plugin.OBSVkCapture
com.obsproject.Studio.Plugin.TransitionTable
com.obsproject.Studio.Plugin.VerticalCanvas
com.opera.Opera
com.play0ad.zeroad
com.plexamp.Plexamp
com.pot_app.pot
com.quexten.Goldwarden
com.redis.RedisInsight
com.steamgriddb.SGDBoop
com.steamgriddb.steam-rom-manager
com.tominlab.wonderpen
com.valvesoftware.Steam.CompatibilityTool.Proton-Exp
com.valvesoftware.Steam.Utility.steamtinkerlaunch
com.visualstudio.code.tool.fish
com.visualstudio.code.tool.podman
com.zhqli.wikit
de.klayout.KLayout
de.sesu8642.feudaltactics
dev.ensoft.ecode
dev.k8slens.OpenLens
dev.pulsar_edit.Pulsar
dev.rdm.RDM
dev.schlaubi.Tonbrett
dev.serebit.Waycheck
dev.skynomads.Seabird
dev.storyapps.starc
eu.quelltext.open_chakra_toning
eu.skribisto.skribisto
eu.vcmi.VCMI
fi.skyjake.Lagrange
ga.rpmtw.rpmlauncher
im.fluffychat.Fluffychat
info.portfolio_performance.PortfolioPerformance
io.beekeeperstudio.Studio
io.conduktor.Conduktor
io.enpass.Enpass
io.github.gopher64.gopher64
io.github.guillaumechereau.Goxel
io.github.Icalingua.Icalingua
io.github.ihhub.Fheroes2
io.github.ilius.pyglossary
io.github.kotatogram
io.github.kukuruzka165.materialgram
io.github.listen1.Listen1
io.github.manisandro.gImageReader
io.github.nearinfinitybrowser.nearinfinity
io.github.sharkwouter.Minigalaxy
io.github.simple64.simple64
io.github.Soundux
io.github.tdesktop_x64.TDesktop
io.github.thaunknown.miru
io.github.troyeguo.koodo-reader
io.github.waylyrics.Waylyrics
io.github.xiaoyifang.goldendict_ng
io.github.xiayifang.goldendict_ng
io.github.yairm210.unciv
io.kopia.KopiaUI
io.wasabiwallet.WasabiWallet
io.wavebox.Wavebox
md.obsidian.Obsidian
me.hyliu.fluentreader
net.agalwood.Motrix
net.blockbench.Blockbench
net.cozic.joplin_desktop
net.mullvad.MullvadBrowser
net.pcsx2.PCSX2
net.rpcs3.RPCS3
net.seamly.seamly2d
net.sourceforge.GrandOrgue
net.veloren.veloren
net.werwolv.ImHex
network.bisq.Bisq
network.loki.Session
nz.mega.MEGAsync
org.apache.jmeter
org.atheme.audacious
org.b3log.siyuan
org.bleachbit.BleachBit
org.cloudcompare.CloudCompare
org.easyrpg.player
org.flarerpg.Flare
org.flathub.flatpak-external-data-checker
org.flightgear.FlightGear
org.flycast.Flycast
org.freedesktop.Platform.VulkanLayer.OBSVkCapture
org.freedesktop.Sdk.Extension.golang
org.freedesktop.Sdk.Extension.node10
org.freedesktop.Sdk.Extension.node12
org.freedesktop.Sdk.Extension.node14
org.freedesktop.Sdk.Extension.node16
org.freedesktop.Sdk.Extension.node18
org.freedesktop.Sdk.Extension.node20
org.freedesktop.Sdk.Extension.php73
org.freedesktop.Sdk.Extension.php74
org.freedesktop.Sdk.Extension.php82
org.freedesktop.Sdk.Extension.rust-nightly
org.freedesktop.Sdk.Extension.rust-stable
org.freedesktop.Sdk.Extension.swift5
org.geogebra.GeoGebra
org.getoutline.OutlineClient
org.getoutline.OutlineManager
org.gnome.Calls
org.goldendict.GoldenDict
org.jabref.jabref
org.kde.KStyle.Kvantum
org.librepcb.LibrePCB
org.mavlink.qgroundcontrol
org.mersenne.mprime
org.naev.Naev
org.octave.Octave
org.openrgb.OpenRGB
org.otfried.Ipe
org.pairinteraction.Pairinteraction
org.pegasus_frontend.Pegasus
org.prismlauncher.PrismLauncher
org.purei.Play
org.qownnotes.QOwnNotes
org.radare.iaito
org.remmina.Remmina
org.signal.Signal
org.soapui.SoapUI
org.standardnotes.standardnotes
org.subsurface_divelog.Subsurface
org.telegram.desktop
org.telegram.desktop.webview
org.texstudio.TeXstudio
org.thonny.Thonny
org.wezfurlong.wezterm
org.zrythm.Zrythm
rocks.koreader.KOReader
ru.yandex.Browser
so.onekey.Wallet
ua.org.brezblock.q4wine
vet.rsc.OpenRSC.Launcher
xyz.armcord.ArmCord
```

</details>

**Comment by xduugu** [comment]
Hey @bbhtt, I noticed today that `com.visualstudio.code.tool.podman` is not updated anymore due to this linter error (see https://github.com/flathub/com.visualstudio.code.tool.podman/pull/62#issuecomment-2234237722). Given that it falls into the same category as `org.freedesktop.Sdk.Extension.golang` and `org.freedesktop.Sdk.Extension.rust-stable`, is there a reason why it didn't get an exception from this rule?

And if it cannot get an exception, what would be the alternative to merging manually? It does not look like the repository is actively maintained.

**Comment by bbhtt** [comment]
Those two are used outside our infra in GNOME's CI who often need latest versions. Not every extension was given the exception.

If com.visualstudio.code.tool.podman needs it, the maintainer needs to open an exception request, with a valid reason on why they need it. Otherwise they have to manually merge.

**Comment by xduugu** [comment]
I see. Thanks a lot for the explanation, @bbhtt.

**Pull request merged**
