### PR TITLE
io.github.dweymouth.supersonic - Update exceptions.json

### PR DESCRIPTION
**Pull request by whorfin**
needs access to `xdg-config/pipewire:ro` for pipewire client config

### CODE REVIEW

**Comment by bbhtt** [comment]
The maintainer is supposed to request exceptions cc @anarcat


Does `--filesystem=~/.config/pipewire:ro` work? Or you need it to be xdg-config specifically?

**Comment by whorfin** [comment]
Yes, I was requesting access for the convenience of the maintainer
`~/.config/pipewire` works for my configuration, but the pipewire docs are explicit about the general case being `$XDG_CONFIG_HOME/pipewire/` for user configurations.

 https://docs.pipewire.org/page_man_pipewire-client_conf_5.html

**Comment by bbhtt** [comment]
Then switch it to that and you'll need no exception. 

If someone keeps xdg-config on a different location, they are on their own to make changes to the sandbox.

**Comment by whorfin** [comment]
Well OK then
I'm just trying to follow standards and make things easy
If you really object, I'll go back to the project and do the "mostly works" solution

**Comment by bbhtt** [comment]
Also static permissions and sharing config from host, should be reduced as much as possible. There is very few people with custom pipewire and pulseaudio configs as most will just use distro defaults.

You can keep that as an override for yourself instead of introducing it for everyone.

**Pull request closed without merging**
