### PR TITLE
Add finish-args-flatpak-spawn-access exception for org.freecad.FreeCAD

### PR DESCRIPTION
**Pull request by adrianinsaval**
see https://github.com/flathub/flathub/pull/5613

### CODE REVIEW

**Comment by adrianinsaval** [comment]
@hfiguiere

**Comment by hfiguiere** [comment]
This is a renaming.

**Comment by adrianinsaval** [comment]
> This is a renaming.

I figured freecadweb exception should stay until migration is done

**Comment by hfiguiere** [comment]
we can remove it when it's archived.

**Pull request merged**
