### PR TITLE
feat: add bavarder exception

### PR DESCRIPTION
**Pull request by 0xMRTT**
Needed for running commands (replace https://github.com/flathub/flatpak-builder-lint/pull/162)

### CODE REVIEW

**Comment by 0xMRTT** [comment]
> I need some more details than "run commands". What commands exactly and why it cannot be accomplished with portals?

It's for running commands outputted by AI...

**Comment by hfiguiere** [comment]
nothing can ever go wrong there...

**Comment by 0xMRTT** [comment]
it's only for allowing user to run the command by clicking on a button, the command can be edited before being run

**Comment by 0xMRTT** [comment]
> Can you update the exception description with these details?

Done!

**Comment by bbhtt** [comment]
Do you still need this? Can you please point how this running command is implemented in your app?

**Comment by bbhtt** [comment]
Please reopen if you need the exception. Closing as this has conflicts and no response.

**Pull request closed without merging**
