### PR TITLE
exceptions: add io.github.nyre221.kiview

### PR DESCRIPTION
**Pull request by Nyre221**
Kiview needs to be able to send commands to the active dolphin window.

### CODE REVIEW

**Comment by bbhtt** [comment]
Linking to the discussion https://github.com/flathub/flathub/pull/5138#discussion_r1554796310

**Comment by bbhtt** [comment]
Can you also add the exception here please https://github.com/flathub-infra/flatpak-builder-lint/blob/524594a8820bfb25ab0cf721714962354e63adee/validator.py#L22

**Comment by bbhtt** [comment]
I meant add `finish-args-wildcard-kde-talk-name` to the validator.py file, not to the json file.

**Comment by Nyre221** [comment]
ah, I was wondering why I had to add that permission.

**Comment by bbhtt** [comment]
Thanks.

**Comment by Nyre221** [comment]
Thank you very much for the help you gave me.

**Pull request merged**
