### PR TITLE
Warn on too long names, summary, missing screenshot captions and project_license

### PR DESCRIPTION
**Pull request by bbhtt**
See https://github.com/flathub-infra/flatpak-builder-lint/issues/156

When name is > 20 characters or summary is > 35 characters

appstreamcli does not warn this, even in pedantic mode.

### CODE REVIEW

**Comment by bbhtt** [comment]
I plan to reuse appstream.py for metainfo, screenshots and desktop file. Otherwise it's the same thing being copied too many times.

`types-lxml` is to provide type hints for lxml, hopefully it works. mypy had to be bumped for that and this bug https://github.com/python/mypy/issues/13627 which prevented using types-lxml.

**Comment by bbhtt** [comment]
Hmm, I just realised names and summary can both have `xml:lang` although it doesn't seem to mentioned here https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-name I need to go through all of them instead of the first one.

**Comment by bbhtt** [comment]
Added a warning on missing `project_license`, appstream-glib allows missing it. There are too many apps missing it sometimes from major desktop groups, so can't do an error but it should be an error otherwise licensing becomes dubious.

**Comment by hfiguiere** [comment]
I do think we should move towards making this an error.

**Comment by bbhtt** [comment]
I would like some data on Flathub before maing it an error.

I'm not against making it an error.

**Comment by razzeee** [comment]
Wondering if we might want to stick these into something like 'appstream-quality-...'

**Comment by bbhtt** [comment]
I don't have a preference.

**Comment by barthalion** [comment]
LGTM. Do we know how many apps will end up failing this?

**Comment by barthalion** [comment]
Welp, there's a merge conflict now. Mind rebasing?

**Comment by bbhtt** [comment]
> LGTM. Do we know how many apps will end up failing this?

Probably a lot, but no idea. I made all the checks warnings for now to stay on the safe side\.

**Comment by razzeee** [comment]
> LGTM. Do we know how many apps will end up failing this?

Login at flathub.org and go to the statistics page

**Comment by bbhtt** [comment]
The quality guidelines are specific to Flathub, appstreamcli is meant to be used outside of it too. The spec doesn't mandate a length

**Comment by razzeee** [comment]
The lengths should also always just be warnings

**Comment by barthalion** [comment]
Warnings should be considered "future deprecations", at least in the current form. People generally don't act upon messages unless they cause CI failures.

**Pull request merged**
